### ISSUE TITLE
Miſſing en daſh (U+2013)

### ISSUE THREAD

**Issue by Alice196498** [ctrlcctrlv/kjv1611#31]
There is no ſort for the en daſh.

**Comment by ctrlcctrlv** [comment]
From what source should I add this glyph?

**Comment by Alice196498** [comment]
I’m admittedly having trouble finding a ſource for it ; perhaps [artistofmind](/artistofmind) knows a good one ? I don’t have a copy of the Bible on-hand, and I amn’t familliar enough with it to cite a uſe from memory ; furthermore, in the few books I do have on-hand, I don’t ſee any en daſhes, but to be fair, they are exceedingly rare, eſpecially in early printing (I can’t recall whether this point was invented yet or not, and even if it be ſo, it might have been like the em daſh, only being widely uſed after 1700).

**Comment by artistofmind** [comment]
Well, the hyphens _do_ vary in width. I suspect this is largely due to varied pressing quality, but may also depend upon word spacing on a given line -- and again, I stress that the majority are quite narrow, almost dot-like in appearance -- but I have cropped one or two wider ones. Perhaps one of those can serve as a basis for the en dash.

The fruits of my massive cropping spree are still forthcoming. I have taken a much-needed break from it (it is very repetitive work), but shall return to it presently, and redouble my efforts.

Cheers to you both.
