### ISSUE TITLE
too much space between "ssw"

### ISSUE THREAD

**Issue by wmichaelshirk** [ctrlcctrlv/kjv1611#36]
the combination of "ssw" results in too much space between all the letters. I can't imagine it's very common - but it is used in the 1662 Book of Common Prayer, prayer "In time of War and Tumults": "abate their pride, asswage their malice, and confound their devices..."
I've attached two screenshots: 
![asswage1](https://user-images.githubusercontent.com/9329923/87867167-04019280-c950-11ea-88ab-540f2cfa8e9b.png)
![asswage2](https://user-images.githubusercontent.com/9329923/87867168-04019280-c950-11ea-955a-08c1bb897f57.png)

**Comment by ctrlcctrlv** [comment]
Sorry, it seems the program you're using is the problem, not my font. You also may be using an old version of the font, please check. Latest is 003.5. But I don't remember fixing this bug, so am not sure it exists in any version. What program?
![image](https://user-images.githubusercontent.com/838783/87867246-f17f5d00-c93f-11ea-98d1-3122e85e7302.png)
![image](https://user-images.githubusercontent.com/838783/87867262-0eb42b80-c940-11ea-8fab-41b7ee59f902.png)

**Comment by wmichaelshirk** [comment]
Interesting. I'm using LuaTeX (1.10) with the fontspec package.

**Comment by wmichaelshirk** [comment]
I do have 3.5 installed both on the system, and in the local folder; (Linux mint 19; TeXLive 2019).  I'm using the hist and calt features: `\setmainfont[RawFeature={+hist,+calt}]{KJV1611.otf}`.  
Anyway, thanks for your work. It's a wonderful font!

**Comment by ctrlcctrlv** [comment]
That is certainly interesting, given that I use a form of TeX to build. :-)

XeLaTeX is used to build (for now, I plan to move to SILE):

https://github.com/ctrlcctrlv/kjv1611/blob/master/info/behold.tex

**Comment by ctrlcctrlv** [comment]
@wmichaelshirk 

I was able to reproduce the issue, but won't be reopening the bug.

I found three LuaLaTeX bugs while investigating your bug:

* ```Package fontspec Warning: Ignored XeTeX-only feature: 'HyphenChar'.``` 🤮 
* Neither `\\` nor `\newline` make a newline in `standalone` class. 🤮🤮 
* Not even `\par` does! WTF? 🤮🤮🤮🤮

# LuaLaTeX
![image](https://user-images.githubusercontent.com/838783/87868777-783b3680-c94e-11ea-8c6e-88874f646b32.png)
# XeLaTeX
![image](https://user-images.githubusercontent.com/838783/87868871-74f47a80-c94f-11ea-96b5-4dd9da0be248.png)

So I won't be fixing your problem...sorry. LuaLaTeX has caused me enough grief for one lifetime. It sucks so much...I'm sure its developers are trying, and the idea is sound, but they've tacked a massive, probably unsolvable, problem, (have all old TeX stuff work \~\*\~but with Lua~*~) and as a consequence, it's so slow, it doesn't work right 90% of the time, etc.

I uncovered another bug while working on it though...seems I forgot a kern for the alternate `u`, or `calt` is doing something else to brick `kern`s. :-) So I will fix that.

Check out [SILE](https://github.com/sile-typesetter/sile). It's also Lua. I wrote a [LaTeXmode](https://github.com/ctrlcctrlv/sile-texmode) for it recently. :-) We have cookies...

**Comment by wmichaelshirk** [comment]
Thank you so much for looking deeper into it!  I'll definitely check out SILE.  I've stuck with TeX mainly because it's the only way to typeset Gregorian Chant that doesn't involve hand-aligning everything. But - when I'm not doing chant - I'd love something easier!

**Comment by ctrlcctrlv** [comment]
@wmichaelshirk Don't sweat it, I was also a big fan of TeX for many years. Familiarity breeds contempt, as the saying goes! :-)

Obviously it's leagues better than say MS Word or InDesign, (at least XeLaTeX is), but when working on SILE you can't help but start to recognize just how much legacy cruft is floating around in the TeX universe, which makes figuring out how to fix anything pretty hard.

Like take LuaLaTeX.

It adds Lua to XeLaTeX which added OpenType to LaTeX2e...assuming I'm even understanding the timeline, big if.

And we're expecting everything to work together in the same document all the way back to METAFONT fonts and T1 encoded packages like TIPA...plus hacks upon hacks like TiKZ that have grown up like weeds over the years and you get a totally unwieldly, incomprehensible system, and when something goes wrong, there's so many places it could have gone wrong in, and so much you have to know to begin investigating (the TeX macro language, XeTeX fontspec internals, LuaLaTeX's language, translation engines between old TeX stuff (TIPA, METAFONT), etc.).

That's why I wrote, "they've tackled a massive, probably unsolvable, problem"...it's just too confusing at this point, so with regret I decided that I am done with the world of *TeX, and moved on to SILE, which although has much less packages, is small enough, and new enough, that I can understand how it works, and contribute the packages I need. :-)

**Comment by alerque** [comment]
> I've stuck with TeX mainly because it's the only way to typeset Gregorian Chant that doesn't involve hand-aligning everything.

This sounds interesting, and also probably not that hard. Please feel free to open a feature request on SILE for this @wmichaelshirk. I'd include a sample of what output you want to achieve, a sample using TeX of what your input looks like now, and also dream a little about what the simplest input you could imagine would look like that has enough information to automatically do whatever needs doing.
