### ISSUE TITLE
j

### ISSUE THREAD

**Issue by artistofmind** [ctrlcctrlv/kjv1611#5]
1. The dot should match the incline of the dot on the "i" glyph. (Cf. Jer. 26:21, Vrijah.)
2. The descender should be slightly longer, and pointy rather than blunt. (Cf. ibid.)

**Comment by ctrlcctrlv** [comment]
Sorry, I think you're wrong based on "j.jpg": https://github.com/ctrlcctrlv/kjv1611/blob/master/KJV%20glyphs/lower/j.jpg

**Comment by artistofmind** [comment]
With respect, I think that image is flawed. Probably because it's a two-tone facsimile. (Note how the dot is actually joined to the stem! Definitely not a clean copy.) I will send you the page with the verse I referenced.
The "j" character is admittedly rare in the Gothic face, since most words usually just have an "i," but the name Vrijah is a particularly good example, since it has both. And, in my reading of this Bible, I have found most "j"s correspond more closely to the one in Jer. 26:21. Including elsewhere in the same book. It is by no means anomalous.

**Comment by ctrlcctrlv** [comment]
Very interesting. There might have actually been two type sorts used, perhaps one for "final j" to be used in the astronomical tables and other listings of figures/verses, and then another "initial/medial j" because it's clear to me that there's no way the dot in "xxxiiij" got bent like that on accident. :)

**Comment by ctrlcctrlv** [comment]
Should be fixed in https://github.com/ctrlcctrlv/kjv1611/commit/0d5a5aed9750ac4bf1cedd38de74efbefde2cd2d (release 3.2)
